version: '3'

services:
  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio-server
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio-data:/data

  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  metastore:
    build: ./hive
    hostname: metastore
    container_name: metastore
    ports:
      - 9083:9083
    volumes:
      - ./hive/metastore-site.xml:/opt/hive/conf/hive-site.xml:ro
      - warehouse:/opt/hive/data/warehouse
    environment:
      DB_HOSTNAME: mysql
      SERVICE_NAME: metastore
    depends_on:
      - mysql
      - minio

  mc-job:
    image: 'minio/mc:latest'
    environment:
      MC_HOST_presto: "http://minioadmin:minioadmin@minio:9000"
    volumes:
      - './minio/data:/minio'
    entrypoint: |
      /bin/bash -c "
      /usr/bin/mc mb --quiet presto/customer-data-text;
      /usr/bin/mc mb --quiet presto/customer-data-orc;
      /usr/bin/mc mirror minio/customer-data-text presto/customer-data-text;
      "
    depends_on:
      - minio
      - metastore

  presto:
    hostname: presto
    image: 'prestodb/presto:0.286-edge13'
    container_name: presto
    ports:
      - '8080:8080'
    volumes:
      - './presto/catalog:/opt/presto-server/etc/catalog'
      - './presto/config.properties:/opt/presto-server/etc/config.properties'
    depends_on:
      - metastore

volumes:
  minio-data:
  mysql-data:
  warehouse:
